function Get-AnyStackLibraryItem {
    <#
    .SYNOPSIS
        Get-AnyStackLibraryItem - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.ContentManager.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Get-AnyStackLibraryItem on server $Server" -ForegroundColor Cyan
    }
}

