function Remove-AnyStackOrphanedIso {
    <#
    .SYNOPSIS
        Remove-AnyStackOrphanedIso - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.ContentManager.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Remove-AnyStackOrphanedIso on server $Server" -ForegroundColor Cyan
    }
}

