function Export-AnyStackAccessMatrix {
    <#
    .SYNOPSIS
        Export-AnyStackAccessMatrix - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.IdentityManager.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Export-AnyStackAccessMatrix on server $Server" -ForegroundColor Cyan
    }
}

