function Get-AnyStackGlobalPermission {
    <#
    .SYNOPSIS
        Get-AnyStackGlobalPermission - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.IdentityManager.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Get-AnyStackGlobalPermission on server $Server" -ForegroundColor Cyan
    }
}

