function Test-AnyStackSsoConfiguration {
    <#
    .SYNOPSIS
        Test-AnyStackSsoConfiguration - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.IdentityManager.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Test-AnyStackSsoConfiguration on server $Server" -ForegroundColor Cyan
    }
}

