function Get-AnyStackFailedScheduledTask {
    <#
    .SYNOPSIS
        Get-AnyStackFailedScheduledTask - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.AutomationOrchestrator.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Get-AnyStackFailedScheduledTask on server $Server" -ForegroundColor Cyan
    }
}

