function Get-AnyStackUntaggedVm {
    <#
    .SYNOPSIS
        Get-AnyStackUntaggedVm - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.TagManager.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Get-AnyStackUntaggedVm on server $Server" -ForegroundColor Cyan
    }
}

