function Sync-AnyStackTagCategory {
    <#
    .SYNOPSIS
        Sync-AnyStackTagCategory - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.TagManager.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Sync-AnyStackTagCategory on server $Server" -ForegroundColor Cyan
    }
}

