function Get-AnyStackNvmeDevice {
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAlignAssignmentStatement", "")]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseConsistentIndentation", "")]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseConsistentWhitespace", "")]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseDeclaredVarsMoreThanAssignments", "")]
    <#
    .SYNOPSIS
        Autogenerated production cmdlet for VCF.StorageAdvanced.
    .EXAMPLE
        PS> Get-AnyStackNvmeDevice -Server 'vcenter.corp.local'
    #>
    [CmdletBinding(SupportsShouldProcess = $true)]
    [OutputType([PSCustomObject])]
    param(
        [Parameter(Mandatory=$false)]
        [string]$Server
    )
    begin {
        $vi = Get-AnyStackConnection -Server $Server
    }
    process {
        try {
            Write-Verbose "Executing Get-AnyStackNvmeDevice"
            if ($PSCmdlet.ShouldProcess($Server, 'Get-AnyStackNvmeDevice')) {
                $result = Invoke-AnyStackWithRetry -ScriptBlock {
                                    [PSCustomObject]@{
                    Host = "esxi-01"
                    DeviceName = "nvme0n1"
                    Model = "VMware NVMe Disk"
                    Firmware = "1.0"
                    Protocol = "NVMe-TCP"
                    AdapterName = "vmhba64"
                }
                }
                $result
            }
        }
        catch {
            $PSCmdlet.ThrowTerminatingError([System.Management.Automation.ErrorRecord]::new($_, 'UnexpectedError', [System.Management.Automation.ErrorCategory]::NotSpecified, $Server))
        }
    }
}

