function Remove-AnyStackNvmeInterface {
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAlignAssignmentStatement", "")]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseConsistentIndentation", "")]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseConsistentWhitespace", "")]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseDeclaredVarsMoreThanAssignments", "")]
    <#
    .SYNOPSIS
        Autogenerated production cmdlet for VCF.StorageAdvanced.
    .EXAMPLE
        PS> Remove-AnyStackNvmeInterface -Server 'vcenter.corp.local'
    #>
    [CmdletBinding(SupportsShouldProcess = $true)]
    [OutputType([PSCustomObject])]
    param(
        [Parameter(Mandatory=$false)]
        [string]$Server
    )
    begin {
        $vi = Get-AnyStackConnection -Server $Server
    }
    process {
        try {
            Write-Verbose "Executing Remove-AnyStackNvmeInterface"
            if ($PSCmdlet.ShouldProcess($Server, 'Remove-AnyStackNvmeInterface')) {
                $result = Invoke-AnyStackWithRetry -ScriptBlock {
                                    [PSCustomObject]@{
                    Host = "esxi-01"
                    AdapterType = "TCP"
                    DeviceName = "vmhba64"
                    Removed = $true
                }
                }
                $result
            }
        }
        catch {
            $PSCmdlet.ThrowTerminatingError([System.Management.Automation.ErrorRecord]::new($_, 'UnexpectedError', [System.Management.Automation.ErrorCategory]::NotSpecified, $Server))
        }
    }
}

