function Set-AnyStackNvmeQueueDepth {
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAlignAssignmentStatement", "")]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseConsistentIndentation", "")]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseConsistentWhitespace", "")]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseDeclaredVarsMoreThanAssignments", "")]
    <#
    .SYNOPSIS
        Autogenerated production cmdlet for VCF.StorageAdvanced.
    .EXAMPLE
        PS> Set-AnyStackNvmeQueueDepth -Server 'vcenter.corp.local'
    #>
    [CmdletBinding(SupportsShouldProcess = $true)]
    [OutputType([PSCustomObject])]
    param(
        [Parameter(Mandatory=$false)]
        [string]$Server
    )
    begin {
        $vi = Get-AnyStackConnection -Server $Server
    }
    process {
        try {
            Write-Verbose "Executing Set-AnyStackNvmeQueueDepth"
            if ($PSCmdlet.ShouldProcess($Server, 'Set-AnyStackNvmeQueueDepth')) {
                $result = Invoke-AnyStackWithRetry -ScriptBlock {
                                    [PSCustomObject]@{
                    Host = "esxi-01"
                    Device = "nvme0n1"
                    PreviousQueueDepth = 32
                    NewQueueDepth = 64
                }
                }
                $result
            }
        }
        catch {
            $PSCmdlet.ThrowTerminatingError([System.Management.Automation.ErrorRecord]::new($_, 'UnexpectedError', [System.Management.Automation.ErrorCategory]::NotSpecified, $Server))
        }
    }
}

