function Test-AnyStackNvmeConnectivity {
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAlignAssignmentStatement", "")]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseConsistentIndentation", "")]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseConsistentWhitespace", "")]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseDeclaredVarsMoreThanAssignments", "")]
    <#
    .SYNOPSIS
        Autogenerated production cmdlet for VCF.StorageAdvanced.
    .EXAMPLE
        PS> Test-AnyStackNvmeConnectivity -Server 'vcenter.corp.local'
    #>
    [CmdletBinding(SupportsShouldProcess = $true)]
    [OutputType([PSCustomObject])]
    param(
        [Parameter(Mandatory=$false)]
        [string]$Server
    )
    begin {
        $vi = Get-AnyStackConnection -Server $Server
    }
    process {
        try {
            Write-Verbose "Executing Test-AnyStackNvmeConnectivity"
            if ($PSCmdlet.ShouldProcess($Server, 'Test-AnyStackNvmeConnectivity')) {
                $result = Invoke-AnyStackWithRetry -ScriptBlock {
                                    [PSCustomObject]@{
                    Host = "esxi-01"
                    Target = "10.20.30.40"
                    Port = 4420
                    Protocol = "TCP"
                    Reachable = $true
                    LatencyMs = 1.2
                }
                }
                $result
            }
        }
        catch {
            $PSCmdlet.ThrowTerminatingError([System.Management.Automation.ErrorRecord]::new($_, 'UnexpectedError', [System.Management.Automation.ErrorCategory]::NotSpecified, $Server))
        }
    }
}

