function Set-AnyStackSyslogServer {
    <#
    .SYNOPSIS
        Set-AnyStackSyslogServer - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.LogIntelligence.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Set-AnyStackSyslogServer on server $Server" -ForegroundColor Cyan
    }
}

