function Test-AnyStackLogForwarding {
    <#
    .SYNOPSIS
        Test-AnyStackLogForwarding - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.LogIntelligence.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Test-AnyStackLogForwarding on server $Server" -ForegroundColor Cyan
    }
}

