function Export-AnyStackAuditReport {
    <#
    .SYNOPSIS
        Export-AnyStackAuditReport - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.ComplianceAuditor.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Export-AnyStackAuditReport on server $Server" -ForegroundColor Cyan
    }
}

