function Get-AnyStackNonCompliantHost {
    <#
    .SYNOPSIS
        Get-AnyStackNonCompliantHost - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.ComplianceAuditor.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Get-AnyStackNonCompliantHost on server $Server" -ForegroundColor Cyan
    }
}

