function Invoke-AnyStackCisStigAudit {
    <#
    .SYNOPSIS
        Invoke-AnyStackCisStigAudit - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.ComplianceAuditor.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Invoke-AnyStackCisStigAudit on server $Server" -ForegroundColor Cyan
    }
}

