function Get-AnyStackHostCpuCoStop {
    <#
    .SYNOPSIS
        Get-AnyStackHostCpuCoStop - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.PerformanceProfiler.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Get-AnyStackHostCpuCoStop on server $Server" -ForegroundColor Cyan
    }
}

