function Test-AnyStackNetworkDroppedPackets {
    <#
    .SYNOPSIS
        Test-AnyStackNetworkDroppedPackets - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.PerformanceProfiler.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Test-AnyStackNetworkDroppedPackets on server $Server" -ForegroundColor Cyan
    }
}

