function Restart-AnyStackVcenterService {
    <#
    .SYNOPSIS
        Restart-AnyStackVcenterService - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.ApplianceManager.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Restart-AnyStackVcenterService on server $Server" -ForegroundColor Cyan
    }
}

