function Test-AnyStackVcenterDatabaseHealth {
    <#
    .SYNOPSIS
        Test-AnyStackVcenterDatabaseHealth - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.ApplianceManager.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Test-AnyStackVcenterDatabaseHealth on server $Server" -ForegroundColor Cyan
    }
}

