function Get-AnyStackZombieVm {
    <#
    .SYNOPSIS
        Get-AnyStackZombieVm - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.CapacityPlanner.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Get-AnyStackZombieVm on server $Server" -ForegroundColor Cyan
    }
}

