function Set-AnyStackRightSizeRecommendation {
    <#
    .SYNOPSIS
        Set-AnyStackRightSizeRecommendation - A specialized AnyStack Enterprise tool.
    .DESCRIPTION
        Autogenerated cmdlet for VCF.CapacityPlanner.
    #>
    [CmdletBinding(SupportsShouldProcess=$true)]
    param(
        [Parameter(Mandatory=$true)] [string]$Server
    )
    process {
        $ErrorActionPreference = 'Stop'
        Write-Host "[ANYSTACK] Running Set-AnyStackRightSizeRecommendation on server $Server" -ForegroundColor Cyan
    }
}

